server = 'wiguard.saurlax.com:3000'

# script to reset the wifi card
init_cmd = 'modprobe -r iwlwifi mac80211 && modprobe iwlwifi connector_log=0x1'
# path to the log_to_file executable
log_cmd = '~/linux-80211n-csitool-supplementary/netlink/log_to_file'
# use for sending data if needed
ping_cmd = '192.168.1.1 -i 0.01'
