[Collection]
send_freq = 5
collect_freq = 0.2
file_template = "csi_"

[Commands]
disconnect = ["sudo", "modprobe", "-r", "iwlwifi", "mac80211"]
reconnect = ["sudo", "modprobe", "iwlwifi", "connector_log=0x1"]
log_to_file = ["~/linux-80211n-csitool-supplementary/netlink/log_to_file"]

[Addresses]
server_addr = "wiguard.saurlax.com:3000"
wifi_ip = "192.168.3.1"
